version: '3'
services:
  react_server:
    container_name: games-public-container
    build:
      context: .
      # DEVELOPMENT
      dockerfile: Dockerfile-public-dev
      # PRODUCTION
      # dockerfile: Dockerfile-public-prod
    image: games-public-image
    ports:
      - 5000:5000
    volumes:
      - ./public:/var/public
  node_server:
    container_name: games-server-container
    build:
      context: .
      dockerfile: Dockerfile-server
    image: games-server-image
    ports:
      - 5001:5001
    volumes:
      - ./server:/var/server